name: Github Actions Debug

on:
  push:
    branches: 
      - develop

jobs:
  build:
    name: Running Units Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
    - name: Compose up the docker
      run: docker-compose -f "docker-compose.yml" up -d --build
    - name: List docker container
      run: docker ps
    - name: Run tests from the built image
      run: docker run survey-form-v2_main_1_main sh -c "npm test"
    - name: Compose down the docker
      run: docker-compose -f "docker-compose.yml" down
